In [1]:
import numpy as np

In [2]:
first_numpy_array=np.array([1,2,3,4])

In [3]:
print(first_numpy_array)

[1 2 3 4]


In [8]:
array_with_zeros=np.zeros((3,3))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
array_with_ones=np.ones((3,3))
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
array_with_empty=np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np_arange=np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
np_arange.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np_linspce=np.linspace(1,6,5)

In [22]:
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [23]:
oneD_array=np.arange(15)

In [24]:
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
twoD_array=oneD_array.reshape(3,5)


In [26]:
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
threeD_array=np.arange(27).reshape(3,3,3)

In [28]:
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [29]:
#NumPy#

In [30]:
import numpy as np

In [31]:
np.array(24)

array(24)

In [32]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [35]:
np.array([[1,2,1],[2,2,3]])

array([[1, 2, 1],
       [2, 2, 3]])

In [36]:
np.array([[[1,2,1],[2,2,3],[4,5,6]]])

array([[[1, 2, 1],
        [2, 2, 3],
        [4, 5, 6]]])

In [37]:
array=np.array([[[1,2,1],[2,2,3],[4,5,6]]])

In [39]:
array.shape

(1, 3, 3)

In [40]:
array.ndim

3

In [41]:
#shapes and axes

In [42]:
numpy_array=np.array([x for x in range(1,10)])
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
numpy_array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
numpy_array=np.array([x for x in range(1,13)])
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
numpy_array.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
numpy_array.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [49]:
numpy_array.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
numpy_array.reshape(2,3,-1) #automatically calculates the dimension of 3rd one

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [52]:
numpy_array.reshape(-1) #flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
#Arithmetic Operations using NumPy

In [54]:
import numpy as np

In [55]:
A=np.array([[1,2,1],[4,5,6]])
B=np.array([7,8,9])

In [56]:
A


array([[1, 2, 1],
       [4, 5, 6]])

In [57]:
B

array([7, 8, 9])

In [58]:
A+B #using '+' operator

array([[ 8, 10, 10],
       [11, 13, 15]])

In [59]:
np.add(A,B)

array([[ 8, 10, 10],
       [11, 13, 15]])

In [60]:
np.subtract(A,B)

array([[-6, -6, -8],
       [-3, -3, -3]])

In [61]:
A-B

array([[-6, -6, -8],
       [-3, -3, -3]])

In [62]:
A*B

array([[ 7, 16,  9],
       [28, 40, 54]])

In [63]:
np.multiply(A,B)

array([[ 7, 16,  9],
       [28, 40, 54]])

In [64]:
A/B

array([[0.14285714, 0.25      , 0.11111111],
       [0.57142857, 0.625     , 0.66666667]])

In [65]:
np.divide(A,B)

array([[0.14285714, 0.25      , 0.11111111],
       [0.57142857, 0.625     , 0.66666667]])

In [66]:
A//B

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [67]:
A%B

array([[1, 2, 1],
       [4, 5, 6]], dtype=int32)

In [68]:
np.power(A,2)

array([[ 1,  4,  1],
       [16, 25, 36]], dtype=int32)

In [69]:
np.power(A,B)

array([[       1,      256,        1],
       [   16384,   390625, 10077696]], dtype=int32)

In [1]:
#condition list
import numpy as np

In [2]:
x=np.array([i for i in range(10)])

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.where(x%2==0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [7]:
condlist=[x<5,x>5]
choicelist=[x**2,x**3]

In [9]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [10]:
#mathematical and statistical functions in numpy

In [11]:
import numpy as np

In [12]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.amin(array)

1

In [14]:
np.amin(array,axis=0) #min valuesnp.om vertical

array([1, 2, 3])

In [15]:
np.amin(array,axis=1) #min values from horizontal

array([1, 4, 7])

In [16]:
np.max(array)

9

In [17]:
np.max(array,axis=0)

array([7, 8, 9])

In [18]:
np.max(array,axis=1)

array([3, 6, 9])

In [19]:
np.mean(array)

5.0

In [20]:
np.median(array)

5.0

In [21]:
np.std(array)

2.581988897471611

In [22]:
np.var(array)

6.666666666666667

In [24]:
np.percentile(array,55) #percentile value (parameters as array and percentile value)

5.4

In [26]:
deg=np.array([0,30,45,60,90])
deg

array([ 0, 30, 45, 60, 90])

In [28]:
np.sin(deg*np.pi/100)

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [29]:
np.cos(deg*np.pi/100)

array([ 1.        ,  0.58778525,  0.15643447, -0.30901699, -0.95105652])

In [30]:
np.tan(deg*np.pi/100)

array([ 0.        ,  1.37638192,  6.31375151, -3.07768354, -0.3249197 ])

In [32]:
arr=np.array([1.2,2.3,5.6,1.4])
arr

array([1.2, 2.3, 5.6, 1.4])

In [33]:
np.floor(arr)

array([1., 2., 5., 1.])

In [34]:
np.ceil(arr)

array([2., 3., 6., 2.])

In [35]:
#indexing and slicing

In [36]:
import numpy as np

In [56]:
array_1D=np.array([1,2,3,4,5,6])
array_2D=np.array([[1,2,3],[4,5,6]])
array_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [40]:
array_1D

array([1, 2, 3, 4, 5, 6])

In [41]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
array_3D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
array_1D[0] #indexing

1

In [44]:
array_1D[2]

3

In [45]:
array_1D[-1]

6

In [46]:
array_2D[1,2]

6

In [47]:
array_2D[-1,2]

6

In [55]:
array_3D[1,1,0]

10

In [57]:
array_1D=np.array([1,2,3,4,5,6])
array_2D=np.array([[1,2,3],[4,5,6]])
array_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [58]:
array_1D

array([1, 2, 3, 4, 5, 6])

In [59]:
array_1D[1:]

array([2, 3, 4, 5, 6])

In [60]:
array_1D[1:5]

array([2, 3, 4, 5])

In [61]:
array_1D[:3]

array([1, 2, 3])

In [62]:
array_1D[1:-1]

array([2, 3, 4, 5])

In [63]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
array_2D[1,2:5]

array([6])

In [66]:
array_2D[1,:-1]

array([4, 5])

In [67]:
array_2D[1,1:]

array([5, 6])

In [68]:
array_2D[-2:-3:-1]

array([[1, 2, 3]])

In [69]:
array_3D[0,1:2:]

array([[4, 5, 6]])